-- MySQL Script generated by MySQL Workbench
-- Fri Jul 29 14:15:41 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lapizza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lapizza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lapizza` DEFAULT CHARACTER SET utf8 ;
USE `lapizza` ;

-- -----------------------------------------------------
-- Table `lapizza`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lapizza`.`Products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_categorie` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `description` TEXT(20000) NULL,
  `price` DECIMAL(10,2) NULL,
  `image` VARCHAR(255) NULL,
  `quantity` INT NULL,
  `status` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lapizza`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lapizza`.`Categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lapizza`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lapizza`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `user` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `type` TINYINT(1) NULL,
  `address` VARCHAR(45) NULL,
  `number` VARCHAR(45) NULL,
  `postal_code` VARCHAR(8) NULL,
  `phone` VARCHAR(20) NULL,
  `status` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lapizza`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lapizza`.`Orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` VARCHAR(45) NULL,
  `subtotal_price` DECIMAL(10,2) NULL,
  `tax_vat` DECIMAL(10,2) NULL,
  `total_price` DECIMAL(10,2) NULL,
  `date` DATETIME NULL,
  `name_user` VARCHAR(45) NULL,
  `address_user` VARCHAR(45) NULL,
  `number_user` VARCHAR(45) NULL,
  `postal_code_user` VARCHAR(45) NULL,
  `phone_user` VARCHAR(45) NULL,
  `name_billing` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lapizza`.`Messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lapizza`.`Messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_order` INT NULL,
  `message` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lapizza`.`Options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lapizza`.`Options` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tax_vat` DECIMAL(10,2) NULL,
  `shipping_region` TEXT(20000) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lapizza`.`Billings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lapizza`.`Billings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lapizza`.`ItensOrder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lapizza`.`ItensOrder` (
  `id_order` INT NULL,
  `id_product` INT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
